		document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' height='100%' background='images/main_bg.gif'>");
			document.write("<tr>");
				document.write("<td>");
					document.write("<table cellpadding='0' cellspacing='0' border='0' width='900' height='100%'>");
						document.write("<tr height='261'>");
							document.write("<td style='background:#f5f5f5 url(images/top7.jpg) top left round no-repeat; border-bottom:1px solid #eaeaea;'>");
								document.write(" <ul id='phoneontop'> ");
									document.write(" <li><i class='fa fa-phone'></i><a href='#'> +1 949-444-2260</a></li> ");
									document.write(" <li><i class='fa fa-envelope'></i><a href='mailto:d321973@mail.com'> d321973@mail.com</a></li> ");
								document.write(" </ul> ");
								
								document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' height='260'>");
									document.write("<tr height='100%'>");
										document.write("<td align='right' style='padding:0px 50px 10px 0px;'>");
											document.write("<table cellpadding='0' cellspacing='0' border='0'>");
												document.write("<tr>");
												document.write("<td align='center' valign='top'>"); 
												document.write("<img src='images/logo.gif' border='0' alt=''><br>");
												document.write("<div class='mycompany'>David Shapiro</div>");
												document.write("<div align='center' class='slogan'>Speed, Relibility and Quality</div>");
												document.write("<a target='_blank' href='https://twitter.com/DimaShapiro' class='fa fa-twitter' style='color: #ffffff'></a> ");
												document.write("<a target='_blank' href='https://www.facebook.com/dimavoron' class='fa fa-facebook' style='color: #ffffff'></a> ");
												document.write("<a href='#' class='fa fa-google' style='color: #ffffff'></a> ");
												document.write("<a href='skype:dima.shapiro' class='fa fa-skype' style='color: #ffffff'></a> ");
												document.write("<a target='_blank' href='https://www.flickr.com/photos/shapirus/' class='fa fa-flickr' style='color: #ffffff'></a> ");
												document.write("<a target='_blank' href='https://www.linkedin.com/in/davidashapiro' class='fa fa-linkedin' style='color: #ffffff'></a> ");
												document.write("</td>");
												document.write("</tr>");
											document.write("</table>");
										document.write("</td>");
									document.write("</tr>");
									document.write("<tr height='26'>");
										document.write("<td style='padding-right:15px;' align='right'>");
