													document.write("</td>");
												document.write("</tr>");
												document.write("<tr>");
													document.write("<td align='right'>");
														document.write("<img src='images/2ndmenu_bottomholes.gif' width='50' height='71' border='0' alt=''>");
													document.write("</td>");
												document.write("</tr>");
											document.write("</table>");
										document.write("</td>");
										document.write("<td width='100%' valign='top' style='border-bottom:1px solid #ffffff; padding:18px 20px 20px 10px;' class='text-bg'>");
											document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' height='100%'>");
												document.write("<tr height='100%'>");
													document.write("<td colspan='2' valign='top'>");
														document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' height='100%' style='border-collapse:collapse;'>");
															document.write("<tr>");
																document.write("<td style='border:1px solid #cccccc;'>");
																	document.write("<table cellpadding='0' cellspacing='0' border='0' width='100%' class='text-header'>");
																		document.write("<tr>");
																			document.write("<td class='text-header'></td>");
																		document.write("</tr>");
																	document.write("</table>");
																document.write("</td>");
															document.write("</tr>");
															document.write("<tr height='100%'>");
																document.write("<td valign='top' style='border:1px solid #cccccc; padding:20px;' bgcolor='#ffffff' class='thatext'>");
																	document.write("<table>");
																		document.write("<tr>");
																			document.write("<td valign='top' width='575' bgcolor='#ffffff' class='thatext'>");
